### ISSUE TITLE
Google SSO

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/eta-meeting-organizer#1]

**Comment by vajgi90** [comment]
Sziasztok! Angularban melyik Module-t használjuk a Social Login kivitelezésére? Van beépített module erre vagy külső lib fog kelleni? Kószó Tomi mondta, csak az ő engedélyével húzhatunk be npm package-et.

**Comment by PumpkinSeed** [comment]
> Sziasztok! Angularban melyik Module-t használjuk a Social Login kivitelezésére? Van beépített module erre vagy külső lib fog kelleni? Kószó Tomi mondta, csak az ő engedélyével húzhatunk be npm package-et.

@ybira Mit ajanlasz?
