### ISSUE TITLE
Full text search meeting room

### ISSUE THREAD

**Issue by PumpkinSeed** [flowacademyhu/eta-meeting-organizer#104]
MySQL megoldas full text search-re a meeting room autocomplite-re.

Input field: "Szeged bajai"
Splitelni kell space alapjan, es minden szora keresni a meeting room neve alapjan. A lowercase-re is.

**Comment by borosr** [comment]
Szerintem ezt bízhatjuk a MySQL-re, úgy látom a 8-as verzió óta támogatott a FTS. Van rá native megoldás [itt](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html), viszont a hibernate is támogatja [itt](https://stackoverflow.com/questions/57683004/how-to-implement-full-text-search-in-spring-boot-with-jpa-mysql). Az utóbbival érdemes lenne futni egy kört a példától generikusabb megoldással.

**Comment by vajgi90** [comment]
Sziasztok! Erre az issue-ra szükség van még? Mivel frontenden paginálunk, sortolunk és filterezünk a Tomival megbeszéltek alapján.
