### ISSUE TITLE
E-mail küldés kiterjesztése frontenden

### ISSUE THREAD

**Issue by dombimihaly89** [flowacademyhu/eta-meeting-organizer#252]
Az email küldésének kiterjesztése a frontend-en.

**Comment by istiFlow** [comment]
Misi mondta hogy a button amivel ki tudjuk törölni az emaileket akiknek ki lesz küldve az esemény azt változtassam meg. a mat-icon  clear ikonjában egyeztünk meg. Maga a font size-ot is megváltoztattam a css-ben 250% ról 225%-ra mert mindenhol azt használjuk ezzel meg is oldódott a scrolling bar ami a title-nél jött elő.
