### ISSUE TITLE
Backend - Profil lekérdezés elkészítése

### ISSUE THREAD

**Issue by borosr** [flowacademyhu/eta-meeting-organizer#41]
#7
Feladatok:

- [x]  Model létrehozása a szükséges adattagokkal
- [x]  Repository létrehozása
- [x]  Resource létrehozása `GET /api/profiles` endpointon - visszaadja az aktuálisan bejelentkezett felhasználó profilját

**Comment by berentepeter** [comment]
a profile-t átírtam userre
